version: "3.9"
services:
  nginx:
    container_name: nginx
    restart: always
    hostname: localhost
    build: ./requirements/nginx
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - nw
    depends_on:
      - wordpress
    ports:
      - "443:443" # https

  mariadb:
    container_name: mariadb
    restart: always
    build: ./requirements/mariadb
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - nw

  wordpress:
    container_name: wordpress
    restart: always
    build: ./requirements/wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - nw
    depends_on:
      - mariadb

volumes:
  db:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb
      o: bind

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind

networks:
  nw:
    driver: bridge
