CREATE DATABASE wordpress;
CREATE USER 'rvinnie'@'%' IDENTIFIED BY '123123';

GRANT ALL PRIVILEGES ON wordpress.* TO 'rvinnie'@'%';

FLUSH PRIVILEGES;

ALTER USER 'root'@'localhost' IDENTIFIED BY 'root123123';